/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sessionId: string;
  paymentIntentId?: string;
  livemode?: boolean;
  total?: number;
  currency?: string;
  items?: Array<{
    productId?: string;
    productName?: string;
    quantity?: number;
    unitPrice?: number;
    _type: "orderItem";
    _key: string;
  }>;
  completedAt?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  aboutBody?: BlockContent;
  termsBody?: BlockContent;
  contactEmail: string;
  shippingRates?: Array<{
    name: string;
    maxWeightGrams?: number;
    price: number;
    _type: "shippingRate";
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  description?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  price: number;
  category: CategoryReference;
  weightInGrams: number;
  deliveryMethod: "post" | "arrange";
  countryOfOrigin?: string;
  isUniquePiece?: boolean;
  stockLevel?: number;
  isFeatured?: boolean;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | BlockContent
  | Order
  | SiteSettings
  | SanityImageAssetReference
  | CategoryReference
  | Product
  | Category
  | Slug
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/queries/sanity.ts
// Variable: IN_STOCK_PRODUCTS_QUERY
// Query: *[_type == "product" && defined(slug.current) && coalesce(stockLevel, 0) > 0]{			_id,	name,	"slug": slug.current,	price,	weightInGrams,	isUniquePiece,	stockLevel,	isFeatured,	_createdAt,	"category": category->{ name, "slug": slug.current },	"image": images[0]{		"url": asset->url,		"alt": alt,		"width": asset->metadata.dimensions.width,		"height": asset->metadata.dimensions.height,		"dominantColor": asset->metadata.palette.dominant.background,		"lqip": asset->metadata.lqip	}	}
export type IN_STOCK_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  price: number;
  weightInGrams: number;
  isUniquePiece: boolean | null;
  stockLevel: number | null;
  isFeatured: boolean | null;
  _createdAt: string;
  category: {
    name: string;
    slug: string;
  };
  image: {
    url: string | null;
    alt: string | null;
    width: number | null;
    height: number | null;
    dominantColor: string | null;
    lqip: string | null;
  } | null;
}>;

// Source: src/queries/sanity.ts
// Variable: FEATURED_PRODUCTS_QUERY
// Query: *[_type == "product" && isFeatured == true && defined(slug.current) && coalesce(stockLevel, 0) > 0]		| order(_createdAt desc)[0...6]{			_id,	name,	"slug": slug.current,	price,	weightInGrams,	isUniquePiece,	stockLevel,	isFeatured,	_createdAt,	"category": category->{ name, "slug": slug.current },	"image": images[0]{		"url": asset->url,		"alt": alt,		"width": asset->metadata.dimensions.width,		"height": asset->metadata.dimensions.height,		"dominantColor": asset->metadata.palette.dominant.background,		"lqip": asset->metadata.lqip	}	}
export type FEATURED_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  price: number;
  weightInGrams: number;
  isUniquePiece: boolean | null;
  stockLevel: number | null;
  isFeatured: boolean | null;
  _createdAt: string;
  category: {
    name: string;
    slug: string;
  };
  image: {
    url: string | null;
    alt: string | null;
    width: number | null;
    height: number | null;
    dominantColor: string | null;
    lqip: string | null;
  } | null;
}>;

// Source: src/queries/sanity.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category" &&		count(*[_type == "product" && category._ref == ^._id && coalesce(stockLevel, 0) > 0]) > 0]{		_id,		name,		"slug": slug.current	} | order(name asc)
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
}>;

// Source: src/queries/sanity.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug][0]{ _id, name, "slug": slug.current }
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
} | null;

// Source: src/queries/sanity.ts
// Variable: PRODUCTS_BY_CATEGORY_QUERY
// Query: *[_type == "product" &&		category._ref in *[_type == "category" && slug.current == $slug]._id &&		defined(slug.current) && coalesce(stockLevel, 0) > 0]{			_id,	name,	"slug": slug.current,	price,	weightInGrams,	isUniquePiece,	stockLevel,	isFeatured,	_createdAt,	"category": category->{ name, "slug": slug.current },	"image": images[0]{		"url": asset->url,		"alt": alt,		"width": asset->metadata.dimensions.width,		"height": asset->metadata.dimensions.height,		"dominantColor": asset->metadata.palette.dominant.background,		"lqip": asset->metadata.lqip	}	}
export type PRODUCTS_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  price: number;
  weightInGrams: number;
  isUniquePiece: boolean | null;
  stockLevel: number | null;
  isFeatured: boolean | null;
  _createdAt: string;
  category: {
    name: string;
    slug: string;
  };
  image: {
    url: string | null;
    alt: string | null;
    width: number | null;
    height: number | null;
    dominantColor: string | null;
    lqip: string | null;
  } | null;
}>;

// Source: src/queries/sanity.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == "product" && slug.current == $slug][0]{		_id,		name,		"slug": slug.current,		description,		price,		weightInGrams,		deliveryMethod,		countryOfOrigin,		isUniquePiece,		stockLevel,		"category": category->{ name, "slug": slug.current },		"images": images[]{			"url": asset->url,			"alt": alt,			"width": asset->metadata.dimensions.width,			"height": asset->metadata.dimensions.height,			"dominantColor": asset->metadata.palette.dominant.background,			"lqip": asset->metadata.lqip		}	}
export type PRODUCT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  description: string | null;
  price: number;
  weightInGrams: number;
  deliveryMethod: "arrange" | "post";
  countryOfOrigin: string | null;
  isUniquePiece: boolean | null;
  stockLevel: number | null;
  category: {
    name: string;
    slug: string;
  };
  images: Array<{
    url: string | null;
    alt: string | null;
    width: number | null;
    height: number | null;
    dominantColor: string | null;
    lqip: string | null;
  }> | null;
} | null;

// Source: src/queries/sanity.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{		aboutBody,		termsBody,		contactEmail,		shippingRates[]{			name,			maxWeightGrams,			price		}	}
export type SITE_SETTINGS_QUERY_RESULT = {
  aboutBody: BlockContent | null;
  termsBody: BlockContent | null;
  contactEmail: string;
  shippingRates: Array<{
    name: string;
    maxWeightGrams: number | null;
    price: number;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n\t*[_type == "product" && defined(slug.current) && coalesce(stockLevel, 0) > 0]{\n\t\t\n\t_id,\n\tname,\n\t"slug": slug.current,\n\tprice,\n\tweightInGrams,\n\tisUniquePiece,\n\tstockLevel,\n\tisFeatured,\n\t_createdAt,\n\t"category": category->{ name, "slug": slug.current },\n\t"image": images[0]{\n\t\t"url": asset->url,\n\t\t"alt": alt,\n\t\t"width": asset->metadata.dimensions.width,\n\t\t"height": asset->metadata.dimensions.height,\n\t\t"dominantColor": asset->metadata.palette.dominant.background,\n\t\t"lqip": asset->metadata.lqip\n\t}\n\n\t}\n': IN_STOCK_PRODUCTS_QUERY_RESULT;
    '\n\t*[_type == "product" && isFeatured == true && defined(slug.current) && coalesce(stockLevel, 0) > 0]\n\t\t| order(_createdAt desc)[0...6]{\n\t\t\n\t_id,\n\tname,\n\t"slug": slug.current,\n\tprice,\n\tweightInGrams,\n\tisUniquePiece,\n\tstockLevel,\n\tisFeatured,\n\t_createdAt,\n\t"category": category->{ name, "slug": slug.current },\n\t"image": images[0]{\n\t\t"url": asset->url,\n\t\t"alt": alt,\n\t\t"width": asset->metadata.dimensions.width,\n\t\t"height": asset->metadata.dimensions.height,\n\t\t"dominantColor": asset->metadata.palette.dominant.background,\n\t\t"lqip": asset->metadata.lqip\n\t}\n\n\t}\n': FEATURED_PRODUCTS_QUERY_RESULT;
    '\n\t*[_type == "category" &&\n\t\tcount(*[_type == "product" && category._ref == ^._id && coalesce(stockLevel, 0) > 0]) > 0]{\n\t\t_id,\n\t\tname,\n\t\t"slug": slug.current\n\t} | order(name asc)\n': CATEGORIES_QUERY_RESULT;
    '\n\t*[_type == "category" && slug.current == $slug][0]{ _id, name, "slug": slug.current }\n': CATEGORY_BY_SLUG_QUERY_RESULT;
    '\n\t*[_type == "product" &&\n\t\tcategory._ref in *[_type == "category" && slug.current == $slug]._id &&\n\t\tdefined(slug.current) && coalesce(stockLevel, 0) > 0]{\n\t\t\n\t_id,\n\tname,\n\t"slug": slug.current,\n\tprice,\n\tweightInGrams,\n\tisUniquePiece,\n\tstockLevel,\n\tisFeatured,\n\t_createdAt,\n\t"category": category->{ name, "slug": slug.current },\n\t"image": images[0]{\n\t\t"url": asset->url,\n\t\t"alt": alt,\n\t\t"width": asset->metadata.dimensions.width,\n\t\t"height": asset->metadata.dimensions.height,\n\t\t"dominantColor": asset->metadata.palette.dominant.background,\n\t\t"lqip": asset->metadata.lqip\n\t}\n\n\t}\n': PRODUCTS_BY_CATEGORY_QUERY_RESULT;
    '\n\t*[_type == "product" && slug.current == $slug][0]{\n\t\t_id,\n\t\tname,\n\t\t"slug": slug.current,\n\t\tdescription,\n\t\tprice,\n\t\tweightInGrams,\n\t\tdeliveryMethod,\n\t\tcountryOfOrigin,\n\t\tisUniquePiece,\n\t\tstockLevel,\n\t\t"category": category->{ name, "slug": slug.current },\n\t\t"images": images[]{\n\t\t\t"url": asset->url,\n\t\t\t"alt": alt,\n\t\t\t"width": asset->metadata.dimensions.width,\n\t\t\t"height": asset->metadata.dimensions.height,\n\t\t\t"dominantColor": asset->metadata.palette.dominant.background,\n\t\t\t"lqip": asset->metadata.lqip\n\t\t}\n\t}\n': PRODUCT_BY_SLUG_QUERY_RESULT;
    '\n\t*[_type == "siteSettings"][0]{\n\t\taboutBody,\n\t\ttermsBody,\n\t\tcontactEmail,\n\t\tshippingRates[]{\n\t\t\tname,\n\t\t\tmaxWeightGrams,\n\t\t\tprice\n\t\t}\n\t}\n': SITE_SETTINGS_QUERY_RESULT;
  }
}
